### ISSUE TITLE
CODIGO ADVINHAS!!

### ISSUE THREAD

**Issue by EFOOSSES** [carreirorco/quartetofgp#1]
#include <iostream>
#include <locale.h>
#include <time.h>
#include <stdio.h>
#include <stdlib.h>
using namespace std;

int main(){

	setlocale(LC_ALL, "Portuguese");
	char nome[50] = {};
	int menu;
	int dificuldade = 2;
	int numero = 0;
	srand(time(NULL));
	int erros = 0;

	while(true){
	system("cls || clear");

	cout << "\t"<< nome << " BEM VINDO AO JOGO DA ADIVINHAÇÃO DE NUMEROS !!\n\n";
	cout << "\t\t\t\t\tMENU\n\n";
	cout << "\t\t\t1. Jogar\n";
	cout << "\t\t\t2. Personalizar meu Nome\n";
	cout << "\t\t\t3. Dificuldade\n";
	cout << "\t\t\t0. Sair\n\n";
    cout << "AUTORES:EVANDRO,RAFAEL,GABRIEL,DOUGLAS!!" <<  endl;
    cin >> menu;

		if(menu>3||menu<1){
			system("cls || clear");
		}
		if(menu==0){
			system("cls || clear");
			cout << "\n\n\n\t\t\t\t" << nome << " Volte Sempre !";
			break;
		}if(menu==2){
			system("cls || clear");
			cout << "\n\n\n\t\t\t\tDigite seu Nick: \n\t\t\t\t";
		    cin >> nome;
		}
		if(menu==3){

			system("cls || clear");
			cout << "\t\t\t\tEscolha a dificuldade !\n\n";
			cout << "\t\t\t1. Facil\n";
			cout << "\t\t\t2. Regular\n";
			cout << "\t\t\t3. Difícil\n";
			cin >> dificuldade;
		}
		if(menu==1){
			erros=0;
			system("cls || clear");
			cout << "\t\t\tDificuldade: ";
			if(dificuldade==1){
				cout << "Facil 0-100\n";
				int gerado =  rand() % 100;
				cout << "tente um valor: ";
				while(true){
					cin >> numero;
					if(numero==gerado){
						cout << "PAPRABÉNS, VOCÊ ACERTOU !!\nTeve " << erros << " erros.\n";
						system("PAUSE");
						break;
					}
					if(numero>gerado){
						cout << "Tente um valor menor: ";
						erros++;
					}
					else{
						cout << "Tente um valor maior: ";
						erros++;
					}
				}
			}

			if(dificuldade==2){
				erros=0;
				cout << "Regular 0-1000\n";
				int gerado = ("%d ", rand() % 1000);
				cout << "tente um valor: ";
			   	while(true){
					cin >> numero;
					if(numero==gerado){
						cout << "PAPRABÉNS, VOCÊ ACERTOU !!\nTeve " << erros << " erros.\n";
						system("PAUSE");
						break;
					}
					if(numero>gerado){
						cout << "Tente um valor menor: ";
						erros++;
					}
					else{
						cout << "Tente um valor maior: ";
						erros++;
					}
				}
			}

			if(dificuldade==3){
				erros=0;
				cout << "Difícil 0-10000\n";
				int gerado = ("%d ", rand() % 10000);
				cout << "tente um valor: ";
				while(true){
					cin >> numero;
					if(numero==gerado){
						cout << "PAPRABÉNS, VOCÊ ACERTOU !!\nTeve " << erros << " erros.\n";
						system("PAUSE");
						break;
					}
					if(numero>gerado){
						cout << "Tente um valor menor: ";
						erros++;
					}
					else{
						cout << "Tente um valor maior: ";
						erros++;
					}
				}
			}
		}
	}

}

**Comment by carreirorco** [comment]
Código inicial feito por Gabriel Manicardi e Evando Osses
